-- V6 khai token_hash là CHAR(64). Trong Postgres, CHAR(n) là kiểu `bpchar` (Types#CHAR),
-- trong khi entity UserSession.tokenHash là String nên Hibernate mong varchar — lệch kiểu
-- và `ddl-auto: validate` chặn app ngay lúc khởi động.
--
-- Đổi CỘT chứ không đổi entity, vì char(n) là lựa chọn sai ngay từ đầu: trong Postgres nó
-- không nhanh hơn varchar(n) một chút nào, lại mang ngữ nghĩa đệm khoảng trắng tới độ dài
-- cố định. Hash SHA-256 hex luôn đúng 64 ký tự nên hôm nay chưa ai thấy hậu quả, nhưng đó
-- là một cái bẫy để nguyên trong schema.
--
-- Sửa thẳng V6 thì gọn hơn nhưng KHÔNG được: V6 đã chạy trên DB thật, và Flyway kiểm
-- checksum — đổi file đã chạy là mọi lần khởi động sau đều fail. Migration append-only
-- (ràng buộc #8).
--
-- UNIQUE index trên cột này được Postgres tự dựng lại theo ALTER, không cần khai lại.
ALTER TABLE user_session ALTER COLUMN token_hash TYPE VARCHAR(64);
